from __future__ import annotations

import importlib.util
import os
import sys
from collections.abc import Generator
from contextlib import contextmanager
from pathlib import Path
from types import ModuleType

import numpy as np
import pandas as pd
import pytest

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib


_BENCHMARK_PATH = Path(__file__).resolve().parent.parent / "benchmarks" / "benchmark.py"
_REPORTING_PATH = Path(__file__).resolve().parent.parent / "benchmarks" / "reporting.py"
_GENERATE_BENCHMARK_DOCS_PATH = (
    Path(__file__).resolve().parent.parent / "benchmarks" / "generate_docs.py"
)
_GENERATED_BENCHMARK_MARKER = (
    "<!-- Generated by pandas-booster benchmark.py; safe to overwrite/delete. -->"
)


def wheel_smoke_mode() -> bool:
    return os.environ.get("PANDAS_BOOSTER_WHEEL_SMOKE") == "1"


def prepend_repo_pythonpath(existing_pythonpath: str | None, repo_python: str) -> str:
    if not existing_pythonpath:
        return repo_python

    entries = [
        entry
        for entry in existing_pythonpath.split(os.pathsep)
        if entry and entry != repo_python
    ]
    return os.pathsep.join([repo_python, *entries])


def pytest_configure(config: pytest.Config) -> None:
    if wheel_smoke_mode():
        return

    repo_python = str(config.rootpath / "python")
    os.environ["PYTHONPATH"] = prepend_repo_pythonpath(
        os.environ.get("PYTHONPATH"),
        repo_python,
    )


def _expected_benchmark_report_aggs() -> tuple[str, ...]:
    return (
        "sum",
        "mean",
        "median",
        "prod",
        "std",
        "var",
        "min",
        "max",
        "count",
    )


def _generated_markdown(body: str) -> str:
    return f"{_GENERATED_BENCHMARK_MARKER}\n\n{body.rstrip()}\n"


@contextmanager
def _loaded_benchmark_module() -> Generator[ModuleType, None, None]:
    sys_path_snapshot = list(sys.path)
    try:
        spec = importlib.util.spec_from_file_location("benchmark_under_test", _BENCHMARK_PATH)
        assert spec is not None
        assert spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        yield module
    finally:
        sys.path[:] = sys_path_snapshot


@contextmanager
def _loaded_generate_benchmark_docs_module() -> Generator[ModuleType, None, None]:
    spec = importlib.util.spec_from_file_location(
        "generate_benchmark_docs_under_test", _GENERATE_BENCHMARK_DOCS_PATH
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    yield module


@pytest.fixture(scope="module")
def benchmark_module():
    with _loaded_benchmark_module() as module:
        yield module


def _make_result(benchmark_module, *, preset: str, agg: str, sort: bool) -> dict:
    stats = benchmark_module.BenchmarkStats(mean=0.1, std=0.01, min=0.09, max=0.11, samples=[0.1])
    return {
        "preset": preset,
        "n_rows": 1_000,
        "n_keys": 1,
        "key_cols": ["key"],
        "combo_cardinality": 100,
        "group_ratio": 0.1,
        "agg": agg,
        "sort": sort,
        "backends": {
            "pandas": {
                "cold_stats": stats,
                "warm_stats": stats,
                "cold_correctness": "not_checked",
                "warm_correctness": "not_checked",
            },
            "booster": {
                "cold_stats": stats,
                "warm_stats": stats,
                "cold_correctness": "pass",
                "warm_correctness": "pass",
            },
        },
    }


def _make_breakdown(
    benchmark_module, *, execution: str = "booster->rust.groupby_std_f64_sorted"
) -> dict:
    stats = benchmark_module.compute_stats([0.1])
    return {
        "execution": execution,
        "phases": {
            "prepare_inputs_s": stats,
            "local_build_s": stats,
            "merge_s": stats,
            "reorder_s": stats,
            "materialize_s": stats,
            "python_normalize_s": stats,
            "python_series_build_s": stats,
            "rust_total_s": stats,
            "python_total_s": stats,
            "total_pipeline_s": stats,
        },
        "rust_total_s": 0.1,
        "python_total_s": 0.1,
        "total_pipeline_s": 0.1,
        "partial_group_total": 1,
        "final_group_count": 1,
        "partial_to_final_ratio": 1.0,
    }


@pytest.fixture
def large_df():
    np.random.seed(42)
    n = 500_000
    return pd.DataFrame(
        {
            "key": np.random.randint(0, 1000, size=n),
            "val_int": np.random.randint(0, 100, size=n),
            "val_float": np.random.random(size=n) * 100,
        }
    )


@pytest.fixture
def small_df():
    return pd.DataFrame(
        {
            "key": [1, 2, 1, 2, 1],
            "val_int": [10, 20, 30, 40, 50],
            "val_float": [1.0, 2.0, 3.0, 4.0, 5.0],
        }
    )


@pytest.fixture
def large_multi_df():
    np.random.seed(42)
    n = 500_000
    return pd.DataFrame(
        {
            "k1": np.random.randint(0, 100, size=n),
            "k2": np.random.randint(0, 50, size=n),
            "k3": np.random.randint(0, 20, size=n),
            "val_int": np.random.randint(0, 100, size=n),
            "val_float": np.random.random(size=n) * 100,
        }
    )


@pytest.fixture
def small_multi_df():
    return pd.DataFrame(
        {
            "k1": [1, 1, 2, 2, 1],
            "k2": [10, 20, 10, 20, 10],
            "val_int": [10, 20, 30, 40, 50],
            "val_float": [1.0, 2.0, 3.0, 4.0, 5.0],
        }
    )


def _load_release_contract_module():
    repo_root = Path(__file__).resolve().parents[1]
    script_path = repo_root / "scripts" / "check_release_contract.py"
    spec = importlib.util.spec_from_file_location("check_release_contract", script_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load release contract script from {script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _project_version() -> str:
    repo_root = Path(__file__).resolve().parents[1]
    with (repo_root / "pyproject.toml").open("rb") as handle:
        return tomllib.load(handle)["project"]["version"]
