from __future__ import annotations

from collections.abc import Sequence

import numpy as np
from numpy.typing import NDArray

I = NDArray[np.int64]
F = NDArray[np.float64]
K = Sequence[I]

RF = tuple[I, F]
RI = tuple[I, I]
P = dict[str, float | int]
PReturnF64 = tuple[I, F, P]

MK = list[I]
MF = tuple[MK, F]
MI = tuple[MK, I]

def get_fallback_threshold() -> int: ...
def get_thread_count() -> int: ...
def has_ordered_single_key_float_prod_abi() -> bool: ...
def groupby_sum_f64(keys: I, values: F) -> RF: ...
def groupby_prod_f64(keys: I, values: F) -> RF: ...
def groupby_mean_f64(keys: I, values: F) -> RF: ...
def groupby_median_f64(keys: I, values: F) -> RF: ...
def groupby_var_f64(keys: I, values: F) -> RF: ...
def groupby_std_f64(keys: I, values: F) -> RF: ...
def groupby_min_f64(keys: I, values: F) -> RF: ...
def groupby_max_f64(keys: I, values: F) -> RF: ...
def groupby_count_f64(keys: I, values: F) -> RI: ...
def groupby_sum_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_prod_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_mean_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_median_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_var_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_std_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_min_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_max_f64_sorted(keys: I, values: F) -> RF: ...
def groupby_count_f64_sorted(keys: I, values: F) -> RI: ...
def profile_groupby_var_f64_sorted(keys: I, values: F) -> PReturnF64: ...
def profile_groupby_std_f64_sorted(keys: I, values: F) -> PReturnF64: ...
def profile_groupby_median_f64_sorted(keys: I, values: F) -> PReturnF64: ...
def groupby_sum_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_sum_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_prod_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_prod_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_mean_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_mean_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_median_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_median_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_var_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_var_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_std_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_std_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_min_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_min_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_max_f64_firstseen_u32(keys: I, values: F) -> RF: ...
def groupby_max_f64_firstseen_u64(keys: I, values: F) -> RF: ...
def groupby_count_f64_firstseen_u32(keys: I, values: F) -> RI: ...
def groupby_count_f64_firstseen_u64(keys: I, values: F) -> RI: ...
def profile_groupby_var_f64_firstseen_u32(keys: I, values: F) -> PReturnF64: ...
def profile_groupby_var_f64_firstseen_u64(keys: I, values: F) -> PReturnF64: ...
def profile_groupby_std_f64_firstseen_u32(keys: I, values: F) -> PReturnF64: ...
def profile_groupby_std_f64_firstseen_u64(keys: I, values: F) -> PReturnF64: ...
def groupby_sum_i64(keys: I, values: I) -> RI: ...
def groupby_prod_i64(keys: I, values: I) -> RI: ...
def groupby_mean_i64(keys: I, values: I) -> RF: ...
def groupby_median_i64(keys: I, values: I) -> RF: ...
def groupby_var_i64(keys: I, values: I) -> RF: ...
def groupby_std_i64(keys: I, values: I) -> RF: ...
def groupby_min_i64(keys: I, values: I) -> RI: ...
def groupby_max_i64(keys: I, values: I) -> RI: ...
def groupby_count_i64(keys: I, values: I) -> RI: ...
def groupby_sum_i64_sorted(keys: I, values: I) -> RI: ...
def groupby_prod_i64_sorted(keys: I, values: I) -> RI: ...
def groupby_mean_i64_sorted(keys: I, values: I) -> RF: ...
def groupby_median_i64_sorted(keys: I, values: I) -> RF: ...
def groupby_var_i64_sorted(keys: I, values: I) -> RF: ...
def groupby_std_i64_sorted(keys: I, values: I) -> RF: ...
def groupby_min_i64_sorted(keys: I, values: I) -> RI: ...
def groupby_max_i64_sorted(keys: I, values: I) -> RI: ...
def groupby_count_i64_sorted(keys: I, values: I) -> RI: ...
def groupby_sum_i64_firstseen_u32(keys: I, values: I) -> RI: ...
def groupby_sum_i64_firstseen_u64(keys: I, values: I) -> RI: ...
def groupby_prod_i64_firstseen_u32(keys: I, values: I) -> RI: ...
def groupby_prod_i64_firstseen_u64(keys: I, values: I) -> RI: ...
def groupby_mean_i64_firstseen_u32(keys: I, values: I) -> RF: ...
def groupby_mean_i64_firstseen_u64(keys: I, values: I) -> RF: ...
def groupby_median_i64_firstseen_u32(keys: I, values: I) -> RF: ...
def groupby_median_i64_firstseen_u64(keys: I, values: I) -> RF: ...
def groupby_var_i64_firstseen_u32(keys: I, values: I) -> RF: ...
def groupby_var_i64_firstseen_u64(keys: I, values: I) -> RF: ...
def groupby_std_i64_firstseen_u32(keys: I, values: I) -> RF: ...
def groupby_std_i64_firstseen_u64(keys: I, values: I) -> RF: ...
def groupby_min_i64_firstseen_u32(keys: I, values: I) -> RI: ...
def groupby_min_i64_firstseen_u64(keys: I, values: I) -> RI: ...
def groupby_max_i64_firstseen_u32(keys: I, values: I) -> RI: ...
def groupby_max_i64_firstseen_u64(keys: I, values: I) -> RI: ...
def groupby_count_i64_firstseen_u32(keys: I, values: I) -> RI: ...
def groupby_count_i64_firstseen_u64(keys: I, values: I) -> RI: ...
def groupby_multi_sum_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_prod_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_mean_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_median_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_var_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_std_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_min_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_max_f64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_count_f64(key_arrays: K, values: F) -> MI: ...
def groupby_multi_sum_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_prod_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_mean_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_median_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_var_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_std_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_min_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_max_f64_sorted(key_arrays: K, values: F) -> MF: ...
def groupby_multi_count_f64_sorted(key_arrays: K, values: F) -> MI: ...
def groupby_multi_sum_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_sum_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_prod_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_prod_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_mean_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_median_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_var_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_std_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_mean_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_median_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_var_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_std_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_min_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_min_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_max_f64_firstseen_u32(key_arrays: K, values: F) -> MF: ...
def groupby_multi_max_f64_firstseen_u64(key_arrays: K, values: F) -> MF: ...
def groupby_multi_count_f64_firstseen_u32(key_arrays: K, values: F) -> MI: ...
def groupby_multi_count_f64_firstseen_u64(key_arrays: K, values: F) -> MI: ...
def groupby_multi_sum_i64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_prod_i64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_mean_i64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_median_i64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_var_i64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_std_i64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_min_i64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_max_i64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_count_i64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_sum_i64_sorted(key_arrays: K, values: I) -> MI: ...
def groupby_multi_prod_i64_sorted(key_arrays: K, values: I) -> MI: ...
def groupby_multi_mean_i64_sorted(key_arrays: K, values: I) -> MF: ...
def groupby_multi_median_i64_sorted(key_arrays: K, values: I) -> MF: ...
def groupby_multi_var_i64_sorted(key_arrays: K, values: I) -> MF: ...
def groupby_multi_std_i64_sorted(key_arrays: K, values: I) -> MF: ...
def groupby_multi_min_i64_sorted(key_arrays: K, values: I) -> MI: ...
def groupby_multi_max_i64_sorted(key_arrays: K, values: I) -> MI: ...
def groupby_multi_count_i64_sorted(key_arrays: K, values: I) -> MI: ...
def groupby_multi_sum_i64_firstseen_u32(key_arrays: K, values: I) -> MI: ...
def groupby_multi_sum_i64_firstseen_u64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_prod_i64_firstseen_u32(key_arrays: K, values: I) -> MI: ...
def groupby_multi_prod_i64_firstseen_u64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_mean_i64_firstseen_u32(key_arrays: K, values: I) -> MF: ...
def groupby_multi_median_i64_firstseen_u32(key_arrays: K, values: I) -> MF: ...
def groupby_multi_var_i64_firstseen_u32(key_arrays: K, values: I) -> MF: ...
def groupby_multi_std_i64_firstseen_u32(key_arrays: K, values: I) -> MF: ...
def groupby_multi_mean_i64_firstseen_u64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_median_i64_firstseen_u64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_var_i64_firstseen_u64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_std_i64_firstseen_u64(key_arrays: K, values: I) -> MF: ...
def groupby_multi_min_i64_firstseen_u32(key_arrays: K, values: I) -> MI: ...
def groupby_multi_min_i64_firstseen_u64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_max_i64_firstseen_u32(key_arrays: K, values: I) -> MI: ...
def groupby_multi_max_i64_firstseen_u64(key_arrays: K, values: I) -> MI: ...
def groupby_multi_count_i64_firstseen_u32(key_arrays: K, values: I) -> MI: ...
def groupby_multi_count_i64_firstseen_u64(key_arrays: K, values: I) -> MI: ...
